import type { KinalatunkCar, FilterSection } from "./types";

export const filterSections: FilterSection[] = [
  { key: "beadas", label: "Badás mód" },
  { key: "marka", label: "Marka" },
  { key: "modell", label: "Modell" },
  { key: "uzemanyag", label: "Üzemanyag típusa" },
  { key: "kivitel", label: "Kivitel" },
  { key: "valto", label: "Váltó típusa" },
  { key: "hajtas", label: "Hajtás" },
  { key: "allapot", label: "Állapot" },
  { key: "kulso", label: "Külső szín" },
  { key: "belso", label: "Belső szín" },
  { key: "okmany", label: "Okmány típusa" },
  { key: "muszaki", label: "Műszaki lejárati dátuma" },
  { key: "statusz", label: "Státusz" },
  { key: "tulajdonsagok", label: "Tulajdonságok" },
];

export const cars: KinalatunkCar[] = [
  {
    id: 1,
    name: "AIXAM CROSSLINE",
    year: "1952",
    price: "4 444Ft",
    image: "/1.jpg",
    featured: true,
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ / CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN / GÁZ (LPG)" },
      { label: "KM. ÓRA ÁLLÁS", value: "7777 km" },
      { label: "HENGERŰRTARTALOM", value: "77777 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA (9 FOKOZATÚ)" },
      { label: "ÁLLAPOT", value: "HIBÁS", red: true },
      { label: "TELJESÍTMÉNY", value: "7777 kW" },
      { label: "", value: "" },
    ],
  },
  {
    id: 2,
    name: "LAMBORGHINI AVENTADOR",
    year: "2023",
    price: "82 000 000Ft",
    image: "/2.jpg",
    featured: true,
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN" },
      { label: "KM. ÓRA ÁLLÁS", value: "12 000 km" },
      { label: "HENGERŰRTARTALOM", value: "6498 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "400 kW" },
      { label: "HELYSZÍN", value: "Budapest, Magyarország" },
    ],
  },
  {
    id: 3,
    name: "ACURA RL",
    year: "2008",
    price: "68 987Ft",
    image: "/3.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN" },
      { label: "KM. ÓRA ÁLLÁS", value: "66 666 km" },
      { label: "HENGERŰRTARTALOM", value: "3500 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA (8 FOKOZATÚ)" },
      { label: "ÁLLAPOT", value: "HIBÁS", red: true },
      { label: "TELJESÍTMÉNY", value: "222 kW" },
      { label: "HELYSZÍN", value: "Debrecen, Magyarország" },
    ],
  },
  {
    id: 4,
    name: "ACURA RL",
    year: "2015",
    price: "4 444Ft",
    image: "/4.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN / GÁZ (LPG)" },
      { label: "KM. ÓRA ÁLLÁS", value: "111 111 km" },
      { label: "HENGERŰRTARTALOM", value: "2400 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA (8 FOKOZATÚ)" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "111 kW" },
      { label: "HELYSZÍN", value: "New York, Egyesült Államok" },
    ],
  },
  {
    id: 5,
    name: "AIWAYS U6",
    year: "2022",
    price: "4 444Ft",
    image: "/5.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ / CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN / GÁZ (LPG)" },
      { label: "KM. ÓRA ÁLLÁS", value: "11 111 km" },
      { label: "HENGERŰRTARTALOM", value: "1500 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "111 kW" },
      { label: "HELYSZÍN", value: "Delhi, India" },
    ],
  },
  {
    id: 6,
    name: "AIXAM CROSSOVER",
    year: "2020",
    price: "33 333Ft",
    image: "/1.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ / CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN" },
      { label: "KM. ÓRA ÁLLÁS", value: "11 111 km" },
      { label: "HENGERŰRTARTALOM", value: "1000 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA (8 FOKOZATÚ)" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "111 kW" },
      { label: "HELYSZÍN", value: "Florida, Egyesült Államok" },
    ],
  },
  {
    id: 7,
    name: "AIXAM CROSSLINE",
    year: "2019",
    price: "4 444Ft",
    image: "/2.jpg",
    featured: true,
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ / CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN / GÁZ (LPG)" },
      { label: "KM. ÓRA ÁLLÁS", value: "333 km" },
      { label: "HENGERŰRTARTALOM", value: "1200 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA" },
      { label: "ÁLLAPOT", value: "HIBÁS", red: true },
      { label: "TELJESÍTMÉNY", value: "88 kW" },
      { label: "HELYSZÍN", value: "Európa" },
    ],
  },
  {
    id: 8,
    name: "ALFA ROMEO 159",
    year: "2010",
    price: "55 555Ft",
    image: "/3.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ / CSERÉLHETŐ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "DÍZEL" },
      { label: "KM. ÓRA ÁLLÁS", value: "180 000 km" },
      { label: "HENGERŰRTARTALOM", value: "2000 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA (8 FOKOZATÚ)" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "125 kW" },
      { label: "HELYSZÍN", value: "Budapest, Magyarország" },
    ],
  },
  {
    id: 9,
    name: "AIXAM CITY",
    year: "2018",
    price: "3 333Ft",
    image: "/4.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "BENZIN / GÁZ (LPG)" },
      { label: "KM. ÓRA ÁLLÁS", value: "33 333 km" },
      { label: "HENGERŰRTARTALOM", value: "333 cm3" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "333 kW" },
      { label: "HELYSZÍN", value: "Szeged, Magyarország" },
    ],
  },
  {
    id: 10,
    name: "AIWAYS 5",
    year: "2021",
    price: "77 676Ft",
    image: "/5.jpg",
    row1: [
      { label: "ELADÁSI MÓD", value: "ELADÓ" },
      { label: "ÜZEMANYAG TÍPUSA", value: "ELEKTROMOS" },
      { label: "KM. ÓRA ÁLLÁS", value: "25 000 km" },
      { label: "HENGERŰRTARTALOM", value: "—" },
    ],
    row2: [
      { label: "VÁLTÓ TÍPUSA", value: "AUTOMATA (8 FOKOZATÚ)" },
      { label: "ÁLLAPOT", value: "ÚJSZERŰ" },
      { label: "TELJESÍTMÉNY", value: "150 kW" },
      { label: "HELYSZÍN", value: "Budapest, Magyarország" },
    ],
  },
];
